version: "3.8"

services:
  react-app:
    container_name: portfolio
    build:
      context: ./website
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./website:/app
    stdin_open: true
    tty: true